export const PRIVILEGED_ACTIONS = [
  "billing.createPaymentAccountOnboarding",
  "billing.openPaymentAccountDashboard",
  "billing.refundPayment",
  "billing.applyInvoiceAdjustment",
  "billing.voidInvoice",
  "subscription.createCheckout",
  "subscription.openBillingPortal",
  "settings.requestAccountDeletion",
  "settings.clearDemoData",
  "settings.reseedDemoData",
  "settings.createUser",
  "settings.inviteStaff",
  "settings.updateUser",
  "settings.deactivateUser",
  "settings.restoreUser",
  "data.exportFullBackup",
  "data.exportClients",
  "data.exportPatients",
  "data.exportAppointments",
  "data.exportInvoices",
  "data.restoreBackup",
  "apiKeys.create",
  "apiKeys.revoke",
  "webhooks.create",
  "webhooks.toggle",
  "webhooks.delete",
  "admin.extendTrial",
  "admin.resolveSmsProviderEvent",
  "admin.setMessagingProfileEnabled",
  "admin.submitMessagingBrand",
  "admin.submitMessagingCampaign",
  "admin.assignMessagingNumbers",
  "admin.reconcileSmsDeliveryEvent",
  "admin.reconcileSmsSendAttempt",
  "admin.resendSmsSendAttempt",
  "admin.attachMessagingProviderIds",
  "admin.clearStaleMessagingSubmissionLock",
  "admin.reconcileMessagingRegistration",
] as const;

export type PrivilegedAction = (typeof PRIVILEGED_ACTIONS)[number];

export const PRIVILEGED_ACTION_LABELS: Record<PrivilegedAction, string> = {
  "billing.createPaymentAccountOnboarding": "Start payment-account onboarding",
  "billing.openPaymentAccountDashboard": "Open payment-account dashboard",
  "billing.refundPayment": "Refund a payment",
  "billing.applyInvoiceAdjustment": "Adjust an invoice",
  "billing.voidInvoice": "Void an invoice",
  "subscription.createCheckout": "Start subscription checkout",
  "subscription.openBillingPortal": "Open subscription billing portal",
  "settings.requestAccountDeletion": "Request clinic account deletion",
  "settings.clearDemoData": "Clear demo data",
  "settings.reseedDemoData": "Reseed demo data",
  "settings.createUser": "Create staff access",
  "settings.inviteStaff": "Invite staff",
  "settings.updateUser": "Change staff access",
  "settings.deactivateUser": "Deactivate staff access",
  "settings.restoreUser": "Restore staff access",
  "data.exportFullBackup": "Export a full clinic backup",
  "data.exportClients": "Export clients",
  "data.exportPatients": "Export patients",
  "data.exportAppointments": "Export appointments",
  "data.exportInvoices": "Export invoices",
  "data.restoreBackup": "Restore a clinic backup",
  "apiKeys.create": "Create an API key",
  "apiKeys.revoke": "Revoke an API key",
  "webhooks.create": "Create a webhook",
  "webhooks.toggle": "Enable or disable a webhook",
  "webhooks.delete": "Delete a webhook",
  "admin.extendTrial": "Extend a clinic trial",
  "admin.resolveSmsProviderEvent": "Resolve an SMS provider event",
  "admin.setMessagingProfileEnabled": "Change a messaging profile state",
  "admin.submitMessagingBrand": "Submit a carrier brand",
  "admin.submitMessagingCampaign": "Submit a carrier campaign",
  "admin.assignMessagingNumbers": "Assign messaging numbers",
  "admin.reconcileSmsDeliveryEvent": "Reconcile an SMS delivery event",
  "admin.reconcileSmsSendAttempt": "Reconcile an SMS send attempt",
  "admin.resendSmsSendAttempt": "Resend an SMS attempt",
  "admin.attachMessagingProviderIds": "Attach carrier provider IDs",
  "admin.clearStaleMessagingSubmissionLock":
    "Clear a stale provider submission lock",
  "admin.reconcileMessagingRegistration": "Reconcile carrier registration",
};

const PRIVILEGED_ACTION_SET = new Set<string>(PRIVILEGED_ACTIONS);

export function isPrivilegedAction(value: unknown): value is PrivilegedAction {
  return typeof value === "string" && PRIVILEGED_ACTION_SET.has(value);
}
